[project]
name = "house-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wei-ann.github", email = "wei-ann.lim@outlook.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pdfplumber>=0.11.10",
    "PyPDF2>=3.0.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
house-management = "house_management:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
